### ISSUE TITLE
No path to target block crash

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer-pathfinder#100]
```
NoPath: No path to target block!
    at Object.error (/mnt/c/Users/Sinan/node_modules/mineflayer-collectblock/lib/Util.js:13:15)
    at EventEmitter.<anonymous> (/mnt/c/Users/Sinan/node_modules/mineflayer-collectblock/lib/CollectBlock.js:74:27)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.monitorMovement (/mnt/c/Users/Sinan/node_modules/mineflayer-pathfinder/index.js:272:15)
    at EventEmitter.emit (events.js:327:22)
    at Timeout.doPhysics [as _onTimeout] (/mnt/c/Users/Sinan/node_modules/mineflayer/lib/plugins/physics.js:63:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

The bot crashes sometimes with no visible reason to me, on 1.16.4 vanilla server.

**Comment by Karang** [comment]
This is an issue of `mineflayer-collectblock`.

**Comment by SinanAkkoyun** [comment]
Oh sure, sorry, wrong tab :o
