### ISSUE TITLE
Example code Type Error

### ISSUE THREAD

**Issue by forerosantiago** [PrismarineJS/mineflayer-pathfinder#115]
Hello, I just found the amazing mineflayer project.

I'm trying to use the example code found [here](https://github.com/PrismarineJS/mineflayer-pathfinder), made small modifications so the bot can login, but the node process crashes when I type a message like follow with the following error:
```bash
/home/runner/mine/node_modules/mineflayer-pathfinder/lib/goals.js:219
    this.x = Math.floor(entity.position.x)
                               ^

TypeError: Cannot read property 'position' of null
    at new GoalFollow (/home/runner/mine/node_modules/mineflayer-pathfinder/lib/goals.js:219:32)
    at EventEmitter.<anonymous> (/home/runner/mine/path.js:70:30)
    at EventEmitter.emit (events.js:315:20)
    at checkForChatPatterns (/home/runner/mine/node_modules/mineflayer/lib/plugins/chat.js:55:60)
    at Client.<anonymous> (/home/runner/mine/node_modules/mineflayer/lib/plugins/chat.js:80:5)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (/home/runner/mine/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (/home/runner/mine/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/runner/mine/node_modules/readable-stream/lib/_stream_readable.js:280:11)
exit status 1
```

My server is running Paper 1.16.4, is this a bug?
Thanks in advance!

**Comment by Karang** [comment]
This mean the bot doesn't see you when you type the command, but its a bug that it doesn't report it. It was fixed for the "come" command but not for "follow". Thanks for reporting.

**Comment by forerosantiago** [comment]
Oh I see, thank you!
