### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by hexatester** [PrismarineJS/mineflayer-pathfinder#119]
I've got this error after updating to `mineflayer-pathfinder@1.6.0`.

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 diggingAborted listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
```

Full trace
```
(node:29885) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 diggingAborted listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)                                     at EventEmitter.addListener (events.js:406:10)
    at resetPath (/data/data/com.termux/files/home/dev/succotash/node_modules/mineflayer-pathfinder/index.js:89:11)
    at EventEmitter.<anonymous> (/data/data/com.termux/files/home/dev/succotash/node_modules/mineflayer-pathfinder/index.js:292:5)
    at EventEmitter.emit (events.js:315:20)                                at addColumn (/data/data/com.termux/files/home/dev/succotash/node_modules/mineflayer/lib/plugins/blocks.js:111:9)
    at Client.<anonymous> (/data/data/com.termux/files/home/dev/succotash/node_modules/mineflayer/lib/plugins/blocks.js:327:5)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (/data/data/com.termux/files/home/dev/succotash/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (events.js:315:20)
(node:29885) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 diggingCompleted listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)
    at EventEmitter.addListener (events.js:406:10)
    at resetPath (/data/data/com.termux/files/home/dev/succotash/node_modules/mineflayer-pathfinder/index.js:90:11)
    at EventEmitter.<anonymous> (/data/data/com.termux/files/home/dev/succotash/node_modules/mineflayer-pathfinder/index.js:292:5)
    at EventEmitter.emit (events.js:315:20)
    at addColumn (/data/data/com.termux/files/home/dev/succotash/node_modules/mineflayer/lib/plugins/blocks.js:111:9)
    at Client.<anonymous> (/data/data/com.termux/files/home/dev/succotash/node_modules/mineflayer/lib/plugins/blocks.js:327:5)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (/data/data/com.termux/files/home/dev/succotash/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (events.js:315:20)
```

**Comment by hexatester** [comment]
I'm using this movement config and running perfectly fine in previous version.

```js
const defaultMove = new Movements(bot, mcData)
defaultMove.canDig = false
```

**Comment by Karang** [comment]
This line was modified already in 1.5.0 but it should be fixed now. Update to 1.6.1 and reopen if you still have the issue.
