### ISSUE TITLE
Type Error: Cannot read property 'X' Of Null

### ISSUE THREAD

**Issue by LostSoul6Years** [PrismarineJS/mineflayer-pathfinder#121]
### Error
`
        } else { throw e }
                   ^

TypeError: Cannot read property 'x' of null
    at isPositionNearPath (C:\Users\jjcde\AppData\Roaming\npm\node_modules\mineflayer-pathfinder\index.js:195:40)
    at EventEmitter.<anonymous> (C:\Users\jjcde\AppData\Roaming\npm\node_modules\mineflayer-pathfinder\index.js:288:9)
    at EventEmitter.emit (events.js:315:20)
    at WorldSync.<anonymous> (C:\Users\jjcde\AppData\Roaming\npm\node_modules\mineflayer\lib\plugins\blocks.js:470:44)
    at WorldSync.emit (events.js:315:20)
    at WorldSync._emitBlockUpdate (C:\Users\jjcde\AppData\Roaming\npm\node_modules\mineflayer\node_modules\prismarine-world\src\worldsync.js:61:10)
    at WorldSync.setBlockStateId (C:\Users\jjcde\AppData\Roaming\npm\node_modules\mineflayer\node_modules\prismarine-world\src\worldsync.js:150:10)
    at updateBlockState (C:\Users\jjcde\AppData\Roaming\npm\node_modules\mineflayer\lib\plugins\blocks.js:257:15)
    at Client.<anonymous> (C:\Users\jjcde\AppData\Roaming\npm\node_modules\mineflayer\lib\plugins\blocks.js:364:5)
    at Client.emit (events.js:315:20)
`
### Request
according to mineflayer api:https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#blockupdate-oldblock-newblock
In BlockUpdate function,oldblock can be null
but your plugin does not handle such type of null error
it is suggested that in the isPositionNearPath function,you add null check error first
then everything will be solved
it can be predicted that more errors like this can show up because as i remember some other events also have null parameters
it is strongly recommended to review the code once a while in order to prevent them thereafter

**Comment by IceTank** [comment]
Thanks has been fixed with #269
