### ISSUE TITLE
Can not handle nicks

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer-pathfinder#126]
The thing is bot.players[target].entity returns true for nicknames but then the bot crashes:

my code: 

```js
if(bot.players[cmd[1]] && bot.players[cmd[1]].entity)
                target = bot.players[cmd[1]].entity
//...

goal_memory = [new goals.GoalFollow(target, 2), (cmd[2] ? (isYes(cmd[2]) ? true : false) : true)]
bot.pathfinder.setGoal(goal_memory[0], goal_memory[1])

```
```
node_modules\mineflayer-pathfinder\lib\goals.js:222
    this.x = Math.floor(entity.position.x)
                               ^

TypeError: Cannot read property 'position' of undefined
    at new GoalFollow (C:\NodeJS-Bot\node_modules\mineflayer-pathfinder\lib\goals.js:222:32)
    at parseCommand (C:\NodeJS-Bot\swarm_bot.js:256:28)
    at run (C:\NodeJS-Bot\swarm_bot.js:130:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by Karang** [comment]
That's an issue with mineflayer. Pathfinder expect you give it a valid entity.
