### ISSUE TITLE
Crash stateGoal.hasChanged not a function

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer-pathfinder#127]
Hi, why is this happening?
```
C:\Users\X\Desktop\SAVE\Minecraft\NodeJS-Bot\node_modules\mineflayer-pathfinder\index.js:313
    if (stateGoal && stateGoal.hasChanged()) {
                               ^

TypeError: stateGoal.hasChanged is not a function
    at EventEmitter.monitorMovement (C:\Users\X\Desktop\SAVE\Minecraft\NodeJS-Bot\node_modules\mineflayer-pathfinder\index.js:313:32)
    at EventEmitter.emit (node:events:390:22)
    at Timeout.doPhysics [as _onTimeout] (C:\Users\Xyun\Desktop\SAVE\Minecraft\NodeJS-Bot\node_modules\mineflayer\lib\plugins\physics.js:63:13)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Comment by SinanAkkoyun** [comment]
My code:

```js
bot.on("playerJoined", (player) => {
        if(goal_memory && goal_memory[0] instanceof goals.GoalFollow && goal_memory[0].entity.username.trim() === player.username.trim()) {
            setTimeout(() => {  //Non blocking while would be better
                if(bot.players[player.username] && bot.players[player.username].entity) {
                
                    bot.pathfinder.setGoal(bot.players[player.username].entity, goal_memory[1])
                
                log("[Pathfinder] Set goal to last memory.")
                } else {
                    log("[Memory] Error, could not get entity of " + player.username + ".")
                }
            }, 3000);
        }
    })
```

btw the bot loses track after a disconnect or world change of the target, likely the entity gets set new then or something

do you know any better way to keep the goal in the bots "memory"?

**Comment by SinanAkkoyun** [comment]
And why is there no function to get the current goal of the pathfinder? Would be so useful

**Comment by Karang** [comment]
You need to read the documentation: https://github.com/PrismarineJS/mineflayer-pathfinder#botpathfindersetgoalgoal-dynamic

`setGoal` expect a goal instance and a boolean, you are giving it an entity and a goal instance. Parameters order and type are not optional, you need to follow the doc and example.

You can get the current goal with `bot.pathfinder.goal`

**Comment by SinanAkkoyun** [comment]
Oh man I am so dumb XD Thank you!!!!
