### ISSUE TITLE
RangeError: Invalid typed array length: Infinity

### ISSUE THREAD

**Issue by Lozarth** [PrismarineJS/mineflayer-pathfinder#287]
```
C:\Users\monko\Downloads\mineflayer>node bot.js
RangeError: Invalid typed array length: Infinity
    at new Uint32Array (<anonymous>)
    at new BitArray (C:\Users\monko\node_modules\prismarine-chunk\src\pc\common\BitArrayNoSpan.js:16:17)
    at new DirectPaletteContainer (C:\Users\monko\node_modules\prismarine-chunk\src\pc\common\PaletteContainer.js:8:17)
    at Function.read (C:\Users\monko\node_modules\prismarine-chunk\src\pc\common\PaletteChunkSection.js:109:15)
    at ChunkColumn.load (C:\Users\monko\node_modules\prismarine-chunk\src\pc\1.18\ChunkColumn.js:246:41)
    at addColumn (C:\Users\monko\node_modules\mineflayer\lib\plugins\blocks.js:57:14)
    at Client.<anonymous> (C:\Users\monko\node_modules\mineflayer\lib\plugins\blocks.js:272:5)
    at Client.emit (node:events:527:28)
    at FullPacketParser.<anonymous> (C:\Users\monko\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:527:28)
RangeError: Invalid typed array length: Infinity
    at new Uint32Array (<anonymous>)
    at new BitArray (C:\Users\monko\node_modules\prismarine-chunk\src\pc\common\BitArrayNoSpan.js:16:17)
    at new DirectPaletteContainer (C:\Users\monko\node_modules\prismarine-chunk\src\pc\common\PaletteContainer.js:8:17)
    at Function.read (C:\Users\monko\node_modules\prismarine-chunk\src\pc\common\PaletteChunkSection.js:109:15)
    at ChunkColumn.load (C:\Users\monko\node_modules\prismarine-chunk\src\pc\1.18\ChunkColumn.js:246:41)
    at addColumn (C:\Users\monko\node_modules\mineflayer\lib\plugins\blocks.js:57:14)
    at Client.<anonymous> (C:\Users\monko\node_modules\mineflayer\lib\plugins\blocks.js:272:5)
    at Client.emit (node:events:527:28)
    at FullPacketParser.<anonymous> (C:\Users\monko\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:527:28)
C:\Users\monko\node_modules\mineflayer\lib\plugins\blocks.js:294
          column.setBlockEntity(blockEntity, blockEntity.nbtData)
                 ^

TypeError: Cannot read properties of undefined (reading 'setBlockEntity')
    at Client.<anonymous> (C:\Users\monko\node_modules\mineflayer\lib\plugins\blocks.js:294:18)
    at Client.emit (node:events:527:28)
    at FullPacketParser.<anonymous> (C:\Users\monko\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:527:28)
    at addChunk (C:\Users\monko\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\monko\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at Readable.push (C:\Users\monko\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at Transform.push (C:\Users\monko\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at FullPacketParser._transform (C:\Users\monko\node_modules\protodef\src\serializer.js:89:10)
    at Transform._read (C:\Users\monko\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:177:10)

Node.js v18.2.0
```

Dunno why its doing this, how can I fix it?

**Comment by Lozarth** [comment]
wrong github repository
