### ISSUE TITLE
(python) TypeError: Cannot read properties of null (reading 'blocksByName')

### ISSUE THREAD

**Issue by dyrkuwu** [PrismarineJS/mineflayer-pathfinder#323]
yeah 
`  at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
  at Socket.Readable.push (node:internal/streams/readable:228:10)
  at readableAddChunk (node:internal/streams/readable:289:9)
  at addChunk (node:internal/streams/readable:315:12)
  at Socket.emit (node:events:390:28)
  at Socket.<anonymous> (C:\Users\naily\AppData\Local\Programs\Python\Python39\lib\site-packages\javascript\js\bridge.js:278:18)
  at Bridge.onMessage (C:\Users\naily\AppData\Local\Programs\Python\Python39\lib\site-packages\javascript\js\bridge.js:226:25)
  at Bridge.call (C:\Users\naily\AppData\Local\Programs\Python\Python39\lib\site-packages\javascript\js\bridge.js:136:42)
  at EventEmitter.loadPlugin (C:\Users\naily\node_modules\mineflayer\lib\plugin_loader.js:25:7)
  at inject (C:\Users\naily\node_modules\mineflayer-pathfinder\index.js:16:28)
> const waterType = mcData.blocksByName.water.id
🌉 TypeError: Cannot read properties of null (reading 'blocksByName')`

**Comment by dyrkuwu** [comment]
Running the python gps.py example

**Comment by dyrkuwu** [comment]
NPM DIDNT UPDATE THE MODULE
