### ISSUE TITLE
Seemingly random crashes "Cannot read property 'y' of undefined"

### ISSUE THREAD

**Issue by L3g7** [PrismarineJS/mineflayer-pathfinder#83]
My bot sometimes throws the error
```
[11:30:54] [AUTORECONNECT] Moving to area
D:\prg\FlayBot_v0.8.9\node_modules\mineflayer-pathfinder\lib\movements.js:81
        height: pos.y + dy
                    ^

TypeError: Cannot read property 'y' of undefined
    at Movements.getBlock (D:\prg\FlayBot_v0.8.9\node_modules\mineflayer-pathfinder\lib\movements.js:81:21)
    at Movements.safeToBreak (D:\prg\FlayBot_v0.8.9\node_modules\mineflayer-pathfinder\lib\movements.js:101:16)
    at Movements.safeOrBreak (D:\prg\FlayBot_v0.8.9\node_modules\mineflayer-pathfinder\lib\movements.js:113:15)
    at Movements.getMoveDiagonal (D:\prg\FlayBot_v0.8.9\node_modules\mineflayer-pathfinder\lib\movements.js:204:18)
    at Movements.getNeighbors (D:\prg\FlayBot_v0.8.9\node_modules\mineflayer-pathfinder\lib\movements.js:350:12)
    at AStar.compute (D:\prg\FlayBot_v0.8.9\node_modules\mineflayer-pathfinder\lib\astar.js:76:40)
    at Object.bot.pathfinder.getPathTo (D:\prg\FlayBot_v0.8.9\node_modules\mineflayer-pathfinder\index.js:39:84)
    at Bot.monitorMovement (D:\prg\FlayBot_v0.8.9\node_modules\mineflayer-pathfinder\index.js:210:26)
    at Bot.emit (events.js:326:22)
    at Timeout.doPhysics [as _onTimeout] (D:\prg\FlayBot_v0.8.9\node_modules\mineflayer\lib\plugins\physics.js:62:13)
Drücken Sie eine beliebige Taste . . . 
```

(Almost) all i have is:
```js
logger.autoreconnect("Moving to area");
var botOptions = {
    host: this.server,
    port: this.port == null ? "25565" : this.port,
    username: this.username,
    password: this.password,
    version: this.version == null ? "1.8.8" : this.version
}

var bot = mineflayer.createBot(botOptions);
bot.loadPlugin(pathfinder);
const mcData = require('minecraft-data')(bot.version);
var defaultMove = new Movements(bot, mcData);
defaultMove.blocksToAvoid.add(mcData.blocksByName.iron_trapdoor.id);
pathfinder(bot)
bot.pathfinder.setMovements(defaultMove);

bot.once('spawn', () => {
    bot.pathfinder.setGoal(new GoalNear(317, 116, 305, 1))
});
```

Usually, this works, but sometimes, seemingly random, the bot crashes and throws the error shown above.
What am i doing wrong?

**Comment by Karang** [comment]
You need to update the package. This bug was fixed.
